---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: adoptopenjdk/openjdk8-openj9
    tag: latest

inputs:
- name: mcmultipart
- name: version

params:
  AWS_ACCESS_KEY_ID: "((aws-access-key-id))"
  AWS_SECRET_ACCESS_KEY: "((aws-secret-access-key))"

caches:
  - path: .gradle/

run:
  path: bash
  args: ["build.sh"]
  dir: mcmultipart
